
apiVersion: v1
kind: Service
metadata:
  name: letsencrypt
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: letsencrypt
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
